[main]
font=JetBrainsMono Nerd Font:size=10
pad=14x14 
initial-window-mode=windowed
workers=0
term=xterm-256color

[cursor]
## beam, block, hollow, underline
style=block
blink=no

[scrollback]
lines=10000
multiplier=7.0

[key-bindings]
clipboard-copy=Control+Insert Control+Shift+c XF86Copy
primary-paste=none
clipboard-paste=Shift+Insert Control+Shift+v XF86Paste

[colors-dark]
foreground=ffffff
background=0a0a0a

regular0=000000  # black
regular1=cc0403  # red
regular2=19cb00  # green
regular3=cecb00  # yellow
regular4=0d73cc  # blue
regular5=cb1ed1  # magenta
regular6=0dcdcd  # cyan
regular7=dddddd  # white

bright0=767676   # bright black
bright1=f2201f   # bright red
bright2=23fd00   # bright green
bright3=fffd00   # bright yellow
bright4=1a8fff   # bright blue
bright5=fd28ff   # bright magenta
bright6=14ffff   # bright cyan
bright7=ffffff   # bright white

## Normal/regular colors (color palette 0-7)
regular0=0a0a0a  # black

alpha=1
